"""add field deleted_at for todos table

Revision ID: ea3151b8d4d6
Revises: 972064ed5a49
Create Date: 2026-05-09 09:57:31.411393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3151b8d4d6'
down_revision: Union[str, None] = '972064ed5a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'deleted_at')
    # ### end Alembic commands ###
